set(SUPPORTS_CXX "FALSE")
if("${COMPILER}" STREQUAL "gnu")
  set(FFLAGS "-fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none")
  set(SUPPORTS_CXX "TRUE")
  set(CFLAGS "-std=gnu99")
  set(CXX_LINKER "FORTRAN")
  set(FC_AUTO_R8 "-fdefault-real-8")
  set(FFLAGS_NOOPT "-O0")
  set(FIXEDFLAGS "-ffixed-form")
  set(FREEFLAGS "-ffree-form")
  set(HAS_F2008_CONTIGUOUS "FALSE")
  set(MPICC "mpicc")
  set(MPICXX "mpicxx")
  set(MPIFC "mpif90")
  set(SCC "gcc")
  set(SCXX "g++")
  set(SFC "gfortran")
endif()
set(CPPDEFS "${CPPDEFS}  -DCESMCOUPLED")
set(CPPDEFS "${CPPDEFS}  -DSYSDARWIN")
if("${MODEL}" STREQUAL "pop")
  set(CPPDEFS "${CPPDEFS}  -D_USE_FLOW_CONTROL")
endif()
if("${MODEL}" STREQUAL "ufsatm")
  set(CPPDEFS "${CPPDEFS}  -DSPMD")
  set(FFLAGS "${FFLAGS}  $(FC_AUTO_R8)")
endif()
if("${MODEL}" STREQUAL "mom")
  set(FFLAGS "${FFLAGS}  $(FC_AUTO_R8) -Duse_LARGEFILE")
endif()
if("${COMPILER}" STREQUAL "gnu")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU")
  set(LDFLAGS "${LDFLAGS}  -framework Accelerate -Wl,-rpath $(NETCDF)/lib")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -fopenmp")
    set(CFLAGS "${CFLAGS}  -fopenmp")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -g -Wall -Og -fbacktrace -ffpe-trap=zero,overflow -fcheck=bounds")
    set(CFLAGS "${CFLAGS}  -g -Wall -Og -fbacktrace -ffpe-trap=invalid,zero,overflow -fcheck=bounds")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(FFLAGS "${FFLAGS}  -O")
    set(CFLAGS "${CFLAGS}  -O")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(LDFLAGS "${LDFLAGS}  -fopenmp")
  endif()
endif()
if("${MODEL}" STREQUAL "ufsatm")
  set(INCLDIR "${INCLDIR}  -I$(EXEROOT)/atm/obj/FMS")
endif()
